version: '3.9'

services:
  pydb:
    container_name: pydb
    image: postgres:latest
    ports:
      - 5050:5432
    environment:
      - POSTGRES_HOST=pydb
      - POSTGRES_USER=theus
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kmdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theus -d kmdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s